//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opbd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string Author { get; set; }
        public byte[] Photo { get; set; }
        public Book()
        { }
        public Book(string N, string D, int P, string A, byte[] Photo)
        {
            this.Name = N;
            this.Description = D;
            this.Price = P;
            this.Author = A;
            this.Photo = Photo;
        }

        public virtual Buy Buy { get; set; }
    }
}
