//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opbd
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Balance { get; set; }
        public string Role { get; set; }
        public string Bought_books { get; set; }
        public User()
        { }
        public User(string Login, string Password, string Email, string Role)
        {
            this.Login = Login;
            this.Password = Password;
            this.Role = Role;
            this.Email = Email;
            this.Balance = 10000;
            this.Bought_books = "";
        }

        public virtual Buy Buy { get; set; }
    }
}
